version: '3.8'

services:
  angular-app:
    image: angular-app
    container_name: angular-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: always
